// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }

"use client"

import React, { ReactNode } from 'react';
import { I18nextProvider } from 'react-i18next';
import i18n from './i18n';
import './globals.css';
import { Inter } from "next/font/google";

interface LayoutProps {
  children: ReactNode; // Define children prop with type ReactNode
}

const inter = Inter({ subsets: ["latin"] })

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <I18nextProvider i18n={i18n}>
      <html lang="en">
       <body className={inter.className}>{children}</body>
      </html>
    </I18nextProvider>
  );
};

export default Layout;
